import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {handle,cleanup,validText} from '../wall-worker/handler.mjs';
function setup(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../wall-worker/schema.sql',import.meta.url),'utf8'));const DB={prepare(sql){let params=[];const out={bind(...values){params=values;return out;},async all(){return {results:db.prepare(sql).all(...params)};},async run(){return {meta:db.prepare(sql).run(...params)};}};return out;},async batch(items){return Promise.all(items.map(s=>s.run()));}};return {env:{DB,MODERATOR_TOKEN:'test-only-'.repeat(5),TURNSTILE_SECRET:'test-secret',ALLOWED_ORIGINS:'https://soberoctober.ru'},db};}
const verify=async()=>new Response(JSON.stringify({success:true,hostname:'soberoctober.ru',action:'wall'}));
const req=(path,method='GET',body,headers={})=>new Request('https://wall.test'+path,{method,headers:{Origin:'https://soberoctober.ru','Content-Type':'application/json',...headers},...(body?{body:JSON.stringify(body)}:{})});
test('public endpoint excludes pending and rejected messages; moderation is authenticated',async()=>{const {env}=setup();const create=await handle(req('/posts','POST',{text:'Погуляла в парке',token:'valid',consent:true}),env,verify);assert.equal(create.status,202);const {id}=await create.json();assert.deepEqual((await (await handle(req('/posts'),env)).json()).posts,[]);assert.equal((await handle(req('/admin/posts'),env)).status,403);const admin=new Request('https://wall.test/admin/posts/'+id,{method:'PATCH',headers:{Origin:'https://wall.test',Authorization:'Bearer '+env.MODERATOR_TOKEN,'Content-Type':'application/json'},body:JSON.stringify({status:'approved'})});assert.equal((await handle(admin,env)).status,200);const posts=(await(await handle(req('/posts'),env)).json()).posts;assert.equal(posts.length,1);assert.equal(posts[0].text,'Погуляла в парке');assert.deepEqual(Object.keys(posts[0]).sort(),['created_at','id','text']);});
test('HTML, contacts, missing consent, wrong origin and invalid captcha are rejected',async()=>{const {env}=setup();assert.equal(validText('<img src=x onerror=alert(1)>'),false);assert.equal(validText('mail@example.com'),false);assert.equal(validText('a'.repeat(401)),false);assert.equal((await handle(req('/posts','POST',{text:'Какао!',token:'x',consent:false}),env,verify)).status,400);assert.equal((await handle(req('/posts','POST',{text:'Какао!',token:'x',consent:true},{Origin:'https://evil.test'}),env,verify)).status,403);const bad=async()=>new Response(JSON.stringify({success:true,hostname:'evil.test',action:'wall'}));assert.equal((await handle(req('/posts','POST',{text:'Какао!',token:'x',consent:true}),env,bad)).status,400);});
test('submission rate is bounded and old pending data is removed',async()=>{const {env,db}=setup();for(let i=0;i<10;i++)assert.equal((await handle(req('/posts','POST',{text:'Чай и книга',token:'x',consent:true}),env,verify)).status,202);assert.equal((await handle(req('/posts','POST',{text:'Ещё чай',token:'x',consent:true}),env,verify)).status,429);db.prepare("INSERT INTO posts(id,text,status,created_at) VALUES ('old','old','pending','2020-01-01')").run();await cleanup(env);assert.equal(db.prepare("SELECT COUNT(*) AS n FROM posts WHERE id='old'").get().n,0);});
test('private admin data requires secret; parser bounds request size',async()=>{const {env}=setup();const admin=new Request('https://wall.test/admin/posts',{headers:{Origin:'https://wall.test'}});assert.equal((await handle(admin,env)).status,401);const big=req('/posts','POST',{text:'x'.repeat(5000),token:'x',consent:true});assert.equal((await handle(big,env)).status,400);});
