import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {resolve} from 'node:path';
const endpoint='https://soberoctober-wall.wall-worker.workers.dev',port=4783,origin=`http://127.0.0.1:${port}`;
let token;
try{const root=execFileSync('powershell.exe',['-NoProfile','-Command','npm root -g'],{encoding:'utf8',windowsHide:true}).trim();const {Entry}=createRequire(import.meta.url)(resolve(root,'@napi-rs/keyring'));token=new Entry('soberoctober','wall-moderator').getPassword();if(!token)throw Error();}catch{console.error('Ключ модератора не найден в системном хранилище. Используйте вход на странице /admin сервиса стены.');process.exit(1);}
const source=await readFile(new URL('../wall-worker/admin.html',import.meta.url),'utf8');
const html=source.replace('</script>',"token='local-proxy';refresh();</script>");
http.createServer(async(req,res)=>{res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','no-referrer');if(req.headers.host!==`127.0.0.1:${port}`){res.writeHead(403);res.end();return;}if(req.headers.origin&&req.headers.origin!==origin){res.writeHead(403);res.end();return;}const path=req.url.split('?')[0];if(path==='/'&&req.method==='GET'){res.setHeader('Content-Type','text/html;charset=utf-8');res.end(html);return;}if(!/^\/admin\/posts(?:\/[a-f0-9-]{36})?$/.test(path)||!['GET','PATCH'].includes(req.method)){res.writeHead(404);res.end();return;}if(req.method==='PATCH'&&req.headers.origin!==origin){res.writeHead(403);res.end();return;}try{let body='';for await(const chunk of req){body+=chunk;if(Buffer.byteLength(body)>4096){res.writeHead(413);res.end();return;}}const upstream=await fetch(endpoint+path,{method:req.method,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},...(body?{body}:{}),signal:AbortSignal.timeout(20000)});res.setHeader('Content-Type','application/json;charset=utf-8');res.writeHead(upstream.status);res.end(await upstream.text());}catch{res.writeHead(503);res.end(JSON.stringify({error:'Не удалось связаться со стеной. Попробуйте позже.'}));}}).listen(port,'127.0.0.1',()=>console.log(`Модерация: ${origin}\nКлюч остаётся в системном хранилище. Закройте окно терминала после работы.`));
