const DAY=86400000;
export function validText(text){return typeof text==='string'&&text.trim().length>=3&&text.trim().length<=400&&!/(https?:\/\/|www\.|<[^>]*>|\b[\w.+-]+@[\w.-]+\.[a-z]{2,}\b)/i.test(text)&&!/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(text);}
async function equalSecret(a,b){if(!a||!b||b.length<32)return false;const hash=async s=>new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));const x=await hash(a),y=await hash(b);let diff=0;for(let i=0;i<x.length;i++)diff|=x[i]^y[i];return diff===0;}
async function jsonBody(request){const reader=request.body?.getReader();if(!reader)throw Error('body');let size=0,chunks=[];for(;;){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>4096){await reader.cancel();throw Error('body');}chunks.push(value);}const all=new Uint8Array(size);let offset=0;for(const chunk of chunks){all.set(chunk,offset);offset+=chunk.length;}return JSON.parse(new TextDecoder().decode(all));}
export async function handle(request,env,verifyFetch=fetch){const url=new URL(request.url),origin=request.headers.get('Origin'),allowed=(env.ALLOWED_ORIGINS||'').split(',').map(v=>v.trim()).filter(Boolean),adminPath=url.pathname.startsWith('/admin/');const headers={'Content-Type':'application/json;charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Robots-Tag':'noindex','Vary':'Origin'};if(allowed.includes(origin))headers['Access-Control-Allow-Origin']=origin;const respond=(data,status=200)=>new Response(JSON.stringify(data),{status,headers});
 if(request.method==='OPTIONS'){if(!allowed.includes(origin))return respond({error:'Origin rejected'},403);return new Response(null,{status:204,headers:{...headers,'Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type','Access-Control-Max-Age':'600'}});}
 if(origin&&origin!==url.origin&&!allowed.includes(origin))return respond({error:'Origin rejected'},403);
 try{
 if(url.pathname==='/health'&&request.method==='GET')return respond({ok:true});
 if(!env.DB)return respond({error:'Стена ещё не подключена.'},503);
 if(adminPath){if(origin&&origin!==url.origin)return respond({error:'Forbidden'},403);if(!await equalSecret(request.headers.get('Authorization')?.replace(/^Bearer /,''),env.MODERATOR_TOKEN))return respond({error:'Неверный ключ модератора.'},401);
 if(url.pathname==='/admin/posts'&&request.method==='GET'){const posts=await env.DB.prepare("SELECT id,text,status,created_at FROM posts ORDER BY created_at DESC LIMIT 200").all();const reports=await env.DB.prepare('SELECT id,post_id,reason,created_at FROM reports ORDER BY created_at DESC LIMIT 100').all();return respond({posts:posts.results,reports:reports.results});}
 const match=url.pathname.match(/^\/admin\/posts\/([a-f0-9-]{36})$/);if(match&&request.method==='PATCH'){const data=await jsonBody(request);if(!['approved','rejected'].includes(data.status))return respond({error:'Unknown status'},400);const result=await env.DB.prepare('UPDATE posts SET status=?,reviewed_at=? WHERE id=?').bind(data.status,new Date().toISOString(),match[1]).run();if(!result.meta.changes)return respond({error:'Запись не найдена'},404);return respond({ok:true});}
 return respond({error:'Not found'},404);}
 if(url.pathname==='/posts'&&request.method==='GET'){const result=await env.DB.prepare("SELECT id,text,created_at FROM posts WHERE status='approved' ORDER BY created_at DESC LIMIT 60").all();return respond({posts:result.results});}
 if(['/posts','/reports'].includes(url.pathname)&&request.method==='POST'){
 if(!allowed.includes(origin))return respond({error:'Origin rejected'},403);
 if(!env.TURNSTILE_SECRET||!env.MODERATOR_TOKEN)return respond({error:'Приём записей временно закрыт.'},503);
 if(!request.headers.get('Content-Type')?.startsWith('application/json'))return respond({error:'Ожидается JSON'},415);
 let data;try{data=await jsonBody(request);}catch{return respond({error:'Проверьте длину и формат записи.'},400);}
 if(data.consent!==true||typeof data.token!=='string'||data.token.length>2048)return respond({error:'Нужно согласие и проверка перед отправкой.'},400);
 if(url.pathname==='/posts'&&!validText(data.text))return respond({error:'От 3 до 400 символов, без ссылок, HTML и контактов.'},400);
 if(url.pathname==='/reports'&&(!/^[a-f0-9-]{36}$/.test(data.postId||'')||!validText(data.reason)))return respond({error:'Проверьте номер записи и причину обращения.'},400);
 const verification=await verifyFetch('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'POST',body:new URLSearchParams({secret:env.TURNSTILE_SECRET,response:data.token})});const checked=await verification.json();const hostnames=allowed.map(o=>new URL(o).hostname);if(!verification.ok||!checked.success||checked.action!=='wall'||!hostnames.includes(checked.hostname))return respond({error:'Проверка не пройдена. Обновите её и попробуйте ещё раз.'},400);
 const now=new Date(),day=now.toISOString().slice(0,10),ip=request.headers.get('CF-Connecting-IP')||'unknown';const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(`${env.MODERATOR_TOKEN}:${day}:${ip}`));const key=Array.from(new Uint8Array(hash),v=>v.toString(16).padStart(2,'0')).join('');const rate=await env.DB.prepare('INSERT INTO rate_limits (key,day,count) VALUES (?,?,1) ON CONFLICT(key) DO UPDATE SET count=count+1 WHERE count<10').bind(key,day).run();if(!rate.meta.changes)return respond({error:'Сегодня уже много отправок. Попробуйте завтра.'},429);
 const id=crypto.randomUUID();if(url.pathname==='/posts')await env.DB.prepare("INSERT INTO posts (id,text,status,created_at) VALUES (?,?,'pending',?)").bind(id,data.text.trim(),now.toISOString()).run();else await env.DB.prepare('INSERT INTO reports (id,post_id,reason,created_at) VALUES (?,?,?,?)').bind(id,data.postId,data.reason.trim(),now.toISOString()).run();return respond({id,status:'pending'},202);
 }
 return respond({error:'Not found'},404);
 }catch{return respond({error:'Стена сейчас недоступна. Попробуйте позже.'},503);}}
export async function cleanup(env){const now=Date.now();await env.DB.batch([env.DB.prepare("DELETE FROM posts WHERE status!='approved' AND created_at<?").bind(new Date(now-30*DAY).toISOString()),env.DB.prepare('DELETE FROM posts WHERE created_at<?').bind(new Date(now-365*DAY).toISOString()),env.DB.prepare('DELETE FROM reports WHERE created_at<?').bind(new Date(now-30*DAY).toISOString()),env.DB.prepare('DELETE FROM rate_limits WHERE day<?').bind(new Date(now-2*DAY).toISOString().slice(0,10))]);}
